use_frameworks!

platform :ios, '11.0'

target 'MVVMCoordinatorKit_Example' do
  pod 'MVVMCoordinatorKit', :path => '../'

  target 'MVVMCoordinatorKit_Tests' do
    inherit! :search_paths

    
  end
end
